version: '3.8'

networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: whatsapp_api
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - instances_connecteds:/codechat/instances
    env_file:
      - .env
    networks:
      - public-network
    links:
      - postgres_server

  postgres_server:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - public-network

volumes:
  instances_connecteds:
    driver: local
  postgres_data:
